import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { BudgetCategory, TxnStatus } from "../../../prisma/generated/prisma";

// Mock webhook handler for development
export async function POST(): Promise<NextResponse> {
  try {
    // Get the first org and card for testing
    const org = await prisma.organization.findFirst();
    const card = await prisma.card.findFirst();

    if (!org || !card) {
      return NextResponse.json(
        { error: "No organization or card found for testing" },
        { status: 404 }
      );
    }

    // Mock transaction data
    const mockTransaction = {
      id: `txn_${Date.now()}`,
      amount: 5000, // $50.00
      currency: "usd",
      status: "succeeded",
      merchant: "Test Merchant",
      category: "office_supplies",
      created: Math.floor(Date.now() / 1000),
    };

    // Map the mock category to our budget category
    const budgetCategory = mapStripeCategoryToBudgetCategory(mockTransaction.category);

    // Create transaction in database
    await prisma.transaction.create({
      data: {
        orgId: org.id,
        cardId: card.id,
        stripeAuthId: mockTransaction.id,
        amountCents: mockTransaction.amount,
        merchant: mockTransaction.merchant,
        category: budgetCategory,
        status: TxnStatus.APPROVED,
        createdAt: new Date(mockTransaction.created * 1000),
      },
    });

    return NextResponse.json({ received: true });
  } catch (error) {
    console.error("Error processing mock webhook:", error);
    return NextResponse.json(
      { error: "Error processing webhook" },
      { status: 500 }
    );
  }
}

// Keep the category mapping function as it's still useful
const mapStripeCategoryToBudgetCategory = (stripeCategory: string): BudgetCategory => {
  const categoryMap: Record<string, BudgetCategory> = {
    "ac_refrigeration_repair": BudgetCategory.EQUIPMENT,
    "accounting_bookkeeping_services": BudgetCategory.TRAINING,
    "advertising_services": BudgetCategory.MARKETING,
    "airlines_air_carriers": BudgetCategory.TRAVEL,
    "apparel_accessory_stores": BudgetCategory.FABRIC_AND_MATERIALS,
    "auto_paint": BudgetCategory.PARTS_AND_MATERIALS,
    "auto_repair_shop": BudgetCategory.EQUIPMENT,
    "automotive_parts_and_accessories_stores": BudgetCategory.PARTS_AND_MATERIALS,
    "automotive_tire_stores": BudgetCategory.PARTS_AND_MATERIALS,
    "bail_and_bond_payments": BudgetCategory.SECURITY,
    "bakeries": BudgetCategory.RETAIL_SPACE,
    "bars_and_nightclubs": BudgetCategory.RETAIL_SPACE,
    "beauty_salons": BudgetCategory.RETAIL_SPACE,
    "bicycle_shops": BudgetCategory.RETAIL_SPACE,
    "book_stores": BudgetCategory.RETAIL_SPACE,
    "business_supplies": BudgetCategory.PARTS_AND_MATERIALS,
    "camera_and_photographic_supply_stores": BudgetCategory.EQUIPMENT,
    "candy_nut_and_confectionery_stores": BudgetCategory.RETAIL_SPACE,
    "car_rental_agencies": BudgetCategory.TRAVEL,
    "car_washes": BudgetCategory.EQUIPMENT,
    "carpentry_services": BudgetCategory.MANUFACTURING,
    "carpet_upholstery_cleaning": BudgetCategory.FABRIC_AND_MATERIALS,
    "caterers": BudgetCategory.RETAIL_SPACE,
    "charitable_and_social_service_organizations": BudgetCategory.MARKETING,
    "chemicals_and_allied_products": BudgetCategory.PARTS_AND_MATERIALS,
    "child_care_services": BudgetCategory.TRAINING,
    "chiropodists_podiatrists": BudgetCategory.TRAINING,
    "chiropractors": BudgetCategory.TRAINING,
    "cigar_stores_and_stands": BudgetCategory.RETAIL_SPACE,
    "cleaning_and_maintenance": BudgetCategory.MANUFACTURING,
    "clothing_rental": BudgetCategory.FABRIC_AND_MATERIALS,
    "colleges_universities": BudgetCategory.TRAINING,
    "commercial_equipment": BudgetCategory.EQUIPMENT,
    "commercial_footwear": BudgetCategory.FABRIC_AND_MATERIALS,
    "commercial_photography_art_and_graphics": BudgetCategory.MARKETING,
    "commuter_transport_and_ferries": BudgetCategory.TRAVEL,
    "computer_network_services": BudgetCategory.EQUIPMENT,
    "computer_programming": BudgetCategory.TRAINING,
    "computer_repair": BudgetCategory.EQUIPMENT,
    "computer_software_stores": BudgetCategory.EQUIPMENT,
    "computers_peripherals_and_software": BudgetCategory.EQUIPMENT,
    "concrete_work_services": BudgetCategory.MANUFACTURING,
    "construction_materials": BudgetCategory.PARTS_AND_MATERIALS,
    "consulting_public_relations": BudgetCategory.TRAINING,
    "correspondence_schools": BudgetCategory.TRAINING,
    "cosmetic_stores": BudgetCategory.RETAIL_SPACE,
    "counseling_services": BudgetCategory.TRAINING,
    "country_clubs": BudgetCategory.RETAIL_SPACE,
    "courier_services": BudgetCategory.TRAVEL,
    "court_costs": BudgetCategory.SECURITY,
    "credit_reporting_agencies": BudgetCategory.INSURANCE,
    "cruise_lines": BudgetCategory.TRAVEL,
    "dairy_products_stores": BudgetCategory.RETAIL_SPACE,
    "dance_hall_studios_schools": BudgetCategory.TRAINING,
    "dating_escort_services": BudgetCategory.MARKETING,
    "dentists_orthodontists": BudgetCategory.TRAINING,
    "department_stores": BudgetCategory.RETAIL_SPACE,
    "detective_agencies": BudgetCategory.SECURITY,
    "direct_marketing_catalog_merchant": BudgetCategory.MARKETING,
    "direct_marketing_combination_catalog_and_retail_merchant": BudgetCategory.MARKETING,
    "direct_marketing_inbound_telemarketing": BudgetCategory.MARKETING,
    "direct_marketing_insurance_services": BudgetCategory.INSURANCE,
    "direct_marketing_other": BudgetCategory.MARKETING,
    "direct_marketing_outbound_telemarketing": BudgetCategory.MARKETING,
    "direct_marketing_subscription": BudgetCategory.MARKETING,
    "direct_marketing_travel": BudgetCategory.TRAVEL,
    "discount_stores": BudgetCategory.RETAIL_SPACE,
    "doctors": BudgetCategory.TRAINING,
    "door_to_door_sales": BudgetCategory.MARKETING,
    "drapery_window_covering_and_upholstery_stores": BudgetCategory.FABRIC_AND_MATERIALS,
    "drinking_places": BudgetCategory.RETAIL_SPACE,
    "drug_stores_and_pharmacies": BudgetCategory.RETAIL_SPACE,
    "drugs_drug_proprietaries_and_druggist_sundries": BudgetCategory.PARTS_AND_MATERIALS,
    "dry_cleaners": BudgetCategory.FABRIC_AND_MATERIALS,
    "durable_goods": BudgetCategory.EQUIPMENT,
    "duty_free_stores": BudgetCategory.RETAIL_SPACE,
    "eating_places_restaurants": BudgetCategory.RETAIL_SPACE,
    "educational_services": BudgetCategory.TRAINING,
    "electric_razor_stores": BudgetCategory.RETAIL_SPACE,
    "electrical_parts_and_equipment": BudgetCategory.PARTS_AND_MATERIALS,
    "electrical_services": BudgetCategory.EQUIPMENT,
    "electronics_repair_shops": BudgetCategory.EQUIPMENT,
    "electronics_stores": BudgetCategory.EQUIPMENT,
    "elementary_secondary_schools": BudgetCategory.TRAINING,
    "employment_temp_agencies": BudgetCategory.TRAINING,
    "equipment_rental": BudgetCategory.EQUIPMENT,
    "exterminating_services": BudgetCategory.MANUFACTURING,
    "family_clothing_stores": BudgetCategory.FABRIC_AND_MATERIALS,
    "fast_food_restaurants": BudgetCategory.RETAIL_SPACE,
    "financial_institutions": BudgetCategory.INSURANCE,
    "fines_government_administrative_entities": BudgetCategory.SECURITY,
    "fireplace_fireplace_screens_and_accessories_stores": BudgetCategory.EQUIPMENT,
    "floor_covering_stores": BudgetCategory.FABRIC_AND_MATERIALS,
    "florists": BudgetCategory.RETAIL_SPACE,
    "florists_supplies_nursery_stock_and_flowers": BudgetCategory.PARTS_AND_MATERIALS,
    "freezer_and_locker_meat_provisioners": BudgetCategory.RETAIL_SPACE,
    "fuel_dealers_non_automotive": BudgetCategory.PARTS_AND_MATERIALS,
    "funeral_services_crematories": BudgetCategory.RETAIL_SPACE,
    "furniture_home_furnishings_and_equipment_stores_except_appliances": BudgetCategory.EQUIPMENT,
    "furniture_repair_refinishing": BudgetCategory.EQUIPMENT,
    "furriers_and_fur_shops": BudgetCategory.FABRIC_AND_MATERIALS,
    "general_services": BudgetCategory.MANUFACTURING,
    "gift_card_novelty_and_souvenir_shops": BudgetCategory.RETAIL_SPACE,
    "glass_paint_and_wallpaper_stores": BudgetCategory.PARTS_AND_MATERIALS,
    "glassware_crystal_stores": BudgetCategory.RETAIL_SPACE,
    "golf_courses_public": BudgetCategory.RETAIL_SPACE,
    "government_services": BudgetCategory.SECURITY,
    "grocery_stores_supermarkets": BudgetCategory.RETAIL_SPACE,
    "hardware_equipment_and_supplies": BudgetCategory.PARTS_AND_MATERIALS,
    "hardware_stores": BudgetCategory.PARTS_AND_MATERIALS,
    "health_and_beauty_spas": BudgetCategory.RETAIL_SPACE,
    "hearing_aids_sales_and_supplies": BudgetCategory.EQUIPMENT,
    "heating_plumbing_a_c": BudgetCategory.EQUIPMENT,
    "jewelry_stores_watches_clocks_and_silverware_stores": BudgetCategory.DIAMOND_INVENTORY,
    "landscaping_services": BudgetCategory.MANUFACTURING,
    "laundries": BudgetCategory.FABRIC_AND_MATERIALS,
    "laundry_cleaning_services": BudgetCategory.FABRIC_AND_MATERIALS,
    "legal_services_attorneys": BudgetCategory.SECURITY,
    "luggage_and_leather_goods_stores": BudgetCategory.FABRIC_AND_MATERIALS,
    "lumber_building_materials_stores": BudgetCategory.PARTS_AND_MATERIALS,
    "manual_cash_disburse": BudgetCategory.INSURANCE,
    "marinas_service_and_supplies": BudgetCategory.EQUIPMENT,
    "masonry_stonework_and_plaster": BudgetCategory.MANUFACTURING,
    "massage_parlors": BudgetCategory.RETAIL_SPACE,
    "medical_and_dental_labs": BudgetCategory.TRAINING,
    "medical_dental_ophthalmic_and_hospital_equipment_and_supplies": BudgetCategory.EQUIPMENT,
    "medical_services": BudgetCategory.TRAINING,
    "membership_organizations": BudgetCategory.MARKETING,
    "mens_and_boys_clothing_and_accessories_stores": BudgetCategory.FABRIC_AND_MATERIALS,
    "mens_womens_clothing_stores": BudgetCategory.FABRIC_AND_MATERIALS,
    "metal_service_centers": BudgetCategory.MANUFACTURING,
    "miscellaneous": BudgetCategory.PARTS_AND_MATERIALS,
    "miscellaneous_apparel_and_accessory_shops": BudgetCategory.FABRIC_AND_MATERIALS,
    "miscellaneous_auto_dealers": BudgetCategory.EQUIPMENT,
    "miscellaneous_business_services": BudgetCategory.MANUFACTURING,
    "miscellaneous_food_stores": BudgetCategory.RETAIL_SPACE,
    "miscellaneous_general_merchandise": BudgetCategory.RETAIL_SPACE,
    "miscellaneous_general_services": BudgetCategory.MANUFACTURING,
    "miscellaneous_home_furnishing_specialty_stores": BudgetCategory.EQUIPMENT,
    "miscellaneous_publishing_and_printing": BudgetCategory.MARKETING,
    "miscellaneous_recreation_services": BudgetCategory.RETAIL_SPACE,
    "miscellaneous_repair_shops": BudgetCategory.EQUIPMENT,
    "miscellaneous_specialty_retail": BudgetCategory.RETAIL_SPACE,
    "mobile_home_dealers": BudgetCategory.RETAIL_SPACE,
    "motion_picture_theaters": BudgetCategory.RETAIL_SPACE,
    "motor_freight_carriers_and_trucking": BudgetCategory.TRAVEL,
    "motor_homes_dealers": BudgetCategory.RETAIL_SPACE,
    "motor_vehicle_supplies_and_new_parts": BudgetCategory.PARTS_AND_MATERIALS,
    "motorcycle_shops_and_dealers": BudgetCategory.RETAIL_SPACE,
    "motorcycle_shops_dealers": BudgetCategory.RETAIL_SPACE,
    "music_stores_musical_instruments_pianos_and_sheet_music": BudgetCategory.EQUIPMENT,
    "news_dealers_and_newsstands": BudgetCategory.RETAIL_SPACE,
    "non_fi_money_orders": BudgetCategory.INSURANCE,
    "non_fi_stored_value_card_purchase_load": BudgetCategory.INSURANCE,
    "nondurable_goods": BudgetCategory.PARTS_AND_MATERIALS,
    "nurseries_lawn_and_garden_supply_stores": BudgetCategory.PARTS_AND_MATERIALS,
    "nursing_personal_care": BudgetCategory.TRAINING,
    "office_and_commercial_furniture": BudgetCategory.EQUIPMENT,
    "opticians_eyeglasses": BudgetCategory.EQUIPMENT,
    "optometrists_ophthalmologist": BudgetCategory.TRAINING,
    "orthopedic_goods_prosthetic_devices": BudgetCategory.EQUIPMENT,
    "osteopaths": BudgetCategory.TRAINING,
    "package_stores_beer_wine_and_liquor": BudgetCategory.RETAIL_SPACE,
    "paints_varnishes_and_supplies": BudgetCategory.PARTS_AND_MATERIALS,
    "parking_lots_garages": BudgetCategory.RETAIL_SPACE,
    "passenger_railways": BudgetCategory.TRAVEL,
    "pawn_shops": BudgetCategory.RETAIL_SPACE,
    "pet_shops_pet_food_and_supplies": BudgetCategory.RETAIL_SPACE,
    "petroleum_and_petroleum_products": BudgetCategory.PARTS_AND_MATERIALS,
    "photo_developing": BudgetCategory.EQUIPMENT,
    "photographic_photocopy_microfilm_equipment_and_supplies": BudgetCategory.EQUIPMENT,
    "photographic_studios": BudgetCategory.MARKETING,
    "picture_video_production": BudgetCategory.MARKETING,
    "piece_goods_notions_and_other_dry_goods": BudgetCategory.FABRIC_AND_MATERIALS,
    "plumbing_heating_equipment_and_supplies": BudgetCategory.PARTS_AND_MATERIALS,
    "political_organizations": BudgetCategory.MARKETING,
    "postal_services_government_only": BudgetCategory.TRAVEL,
    "precious_stones_and_metals_watches_and_jewelry": BudgetCategory.DIAMOND_INVENTORY,
    "professional_services": BudgetCategory.TRAINING,
    "public_warehousing_and_storage": BudgetCategory.MANUFACTURING,
    "quick_copy_repro_and_blueprint": BudgetCategory.MARKETING,
    "railroads": BudgetCategory.TRAVEL,
    "real_estate_agents_and_managers_rentals": BudgetCategory.RETAIL_SPACE,
    "record_stores": BudgetCategory.RETAIL_SPACE,
    "recreational_vehicle_rentals": BudgetCategory.TRAVEL,
    "religious_goods_stores": BudgetCategory.RETAIL_SPACE,
    "religious_organizations": BudgetCategory.MARKETING,
    "roofing_siding_sheet_metal": BudgetCategory.MANUFACTURING,
    "secretarial_support_services": BudgetCategory.TRAINING,
    "security_brokers_dealers": BudgetCategory.SECURITY,
    "service_stations": BudgetCategory.RETAIL_SPACE,
    "sewing_needlework_fabric_and_piece_goods_stores": BudgetCategory.FABRIC_AND_MATERIALS,
    "shoe_repair_hat_cleaning": BudgetCategory.FABRIC_AND_MATERIALS,
    "shoe_stores": BudgetCategory.FABRIC_AND_MATERIALS,
    "small_appliance_repair": BudgetCategory.EQUIPMENT,
    "snowmobile_dealers": BudgetCategory.RETAIL_SPACE,
    "special_trade_services": BudgetCategory.MANUFACTURING,
    "specialty_cleaning": BudgetCategory.MANUFACTURING,
    "sporting_goods_stores": BudgetCategory.RETAIL_SPACE,
    "sporting_recreation_camps": BudgetCategory.RETAIL_SPACE,
    "sports_and_riding_apparel_stores": BudgetCategory.FABRIC_AND_MATERIALS,
    "sports_clubs_fields": BudgetCategory.RETAIL_SPACE,
    "stamp_and_coin_stores": BudgetCategory.RETAIL_SPACE,
    "stationary_office_supplies_printing_and_writing_paper": BudgetCategory.PARTS_AND_MATERIALS,
    "stationery_stores_office_and_school_supply_stores": BudgetCategory.PARTS_AND_MATERIALS,
    "swimming_pools_sales": BudgetCategory.EQUIPMENT,
    "t_ui_travel_germany": BudgetCategory.TRAVEL,
    "tailors_alterations": BudgetCategory.FABRIC_AND_MATERIALS,
    "tax_payments_government_agencies": BudgetCategory.SECURITY,
    "tax_preparation_services": BudgetCategory.TRAINING,
    "taxicabs_limousines": BudgetCategory.TRAVEL,
    "telecommunication_equipment_and_telephone_sales": BudgetCategory.EQUIPMENT,
    "telecommunication_services": BudgetCategory.EQUIPMENT,
    "telegraph_services": BudgetCategory.EQUIPMENT,
    "tent_and_awning_shops": BudgetCategory.FABRIC_AND_MATERIALS,
    "testing_laboratories": BudgetCategory.TRAINING,
    "theatrical_ticket_agencies": BudgetCategory.RETAIL_SPACE,
    "timeshares": BudgetCategory.RETAIL_SPACE,
    "tire_retreading_and_repair": BudgetCategory.PARTS_AND_MATERIALS,
    "tolls_bridge_fees": BudgetCategory.TRAVEL,
    "tourist_attractions_and_exhibits": BudgetCategory.RETAIL_SPACE,
    "towing_services": BudgetCategory.EQUIPMENT,
    "trailer_parks_campgrounds": BudgetCategory.RETAIL_SPACE,
    "transportation_services": BudgetCategory.TRAVEL,
    "travel_agencies_tour_operators": BudgetCategory.TRAVEL,
    "truck_stop_iteration": BudgetCategory.TRAVEL,
    "truck_utility_trailer_rentals": BudgetCategory.TRAVEL,
    "typesetting_plate_making_and_related_services": BudgetCategory.MARKETING,
    "typewriter_stores": BudgetCategory.EQUIPMENT,
    "u_s_federal_government_agencies_or_departments": BudgetCategory.SECURITY,
    "uniforms_commercial_clothing": BudgetCategory.FABRIC_AND_MATERIALS,
    "used_merchandise_and_secondhand_stores": BudgetCategory.RETAIL_SPACE,
    "utilities": BudgetCategory.EQUIPMENT,
    "variety_stores": BudgetCategory.RETAIL_SPACE,
    "veterinary_services": BudgetCategory.TRAINING,
    "video_amusement_game_supplies": BudgetCategory.EQUIPMENT,
    "video_game_arcades": BudgetCategory.RETAIL_SPACE,
    "video_tape_rental_stores": BudgetCategory.RETAIL_SPACE,
    "vocational_trade_schools": BudgetCategory.TRAINING,
    "watch_jewelry_repair": BudgetCategory.DIAMOND_INVENTORY,
    "welding_repair": BudgetCategory.EQUIPMENT,
    "wholesale_clubs": BudgetCategory.RETAIL_SPACE,
    "wig_and_toupee_stores": BudgetCategory.FABRIC_AND_MATERIALS,
    "wires_money_orders": BudgetCategory.INSURANCE,
    "womens_accessory_and_specialty_shops": BudgetCategory.FABRIC_AND_MATERIALS,
    "womens_ready_to_wear_stores": BudgetCategory.FABRIC_AND_MATERIALS,
    "wrecking_and_salvage_yards": BudgetCategory.MANUFACTURING,
  };

  return categoryMap[stripeCategory] || BudgetCategory.PARTS_AND_MATERIALS;
};
